### ISSUE TITLE
[feature] segment path

### ISSUE THREAD

**Issue by yorshex** [Shatter-Team/Shatter#21]
make the user able to set segment path manually instead of setting it by the level, room and segment name

**Comment by knot126** [comment]
Would it be okay if I just ignored weather the level and room are set if the segment name is set, and only use the segment name in that case? I would really prefer not to make more options in the Blender UI.

**Comment by yorshex** [comment]
@knot126 yes, i would

**Comment by knot126** [comment]
Done
