### ISSUE TITLE
[client improvement] remove hints

### ISSUE THREAD

**Issue by yorshex** [Shatter-Team/Shatter#23]
hints are shown at the bottom of the screen if your distance is less than 1000
hints are shown in `frame()` in `/assets/hud/main.lua`
i suggest to remove the hint code from the client cuz it's unneeded and annoying

**Comment by knot126** [comment]
I'll do this, and also remove the "restart checkpoint" prompt since it's broken and not really needed. The client needs an update, I've just not gotten to that yet.

**Comment by yorshex** [comment]
you can also remove power up hints
such as an arrow, that point to power-up point, and "press, infinite balls message"

**Comment by knot126** [comment]
Late to close, but this is done in v3.3.1
